// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sbhub.proto

package com.townsendsoftware.sbhub.protos;

/**
 * Protobuf type {@code com.townsendsoftware.sbhub.protos.FibonacciSequence}
 */
public  final class FibonacciSequence extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.townsendsoftware.sbhub.protos.FibonacciSequence)
    FibonacciSequenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FibonacciSequence.newBuilder() to construct.
  private FibonacciSequence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FibonacciSequence() {
    version_ = 0;
    count_ = 0;
    sequence_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FibonacciSequence(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            count_ = input.readInt32();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              sequence_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            sequence_.add(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              sequence_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              sequence_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        sequence_ = java.util.Collections.unmodifiableList(sequence_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.townsendsoftware.sbhub.protos.FibonacciSequence.class, com.townsendsoftware.sbhub.protos.FibonacciSequence.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private int count_;
  /**
   * <code>int32 count = 2;</code>
   */
  public int getCount() {
    return count_;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Long> sequence_;
  /**
   * <code>repeated int64 sequence = 4;</code>
   */
  public java.util.List<java.lang.Long>
      getSequenceList() {
    return sequence_;
  }
  /**
   * <code>repeated int64 sequence = 4;</code>
   */
  public int getSequenceCount() {
    return sequence_.size();
  }
  /**
   * <code>repeated int64 sequence = 4;</code>
   */
  public long getSequence(int index) {
    return sequence_.get(index);
  }
  private int sequenceMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (count_ != 0) {
      output.writeInt32(2, count_);
    }
    if (getSequenceList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(sequenceMemoizedSerializedSize);
    }
    for (int i = 0; i < sequence_.size(); i++) {
      output.writeInt64NoTag(sequence_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, count_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sequence_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(sequence_.get(i));
      }
      size += dataSize;
      if (!getSequenceList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      sequenceMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.townsendsoftware.sbhub.protos.FibonacciSequence)) {
      return super.equals(obj);
    }
    com.townsendsoftware.sbhub.protos.FibonacciSequence other = (com.townsendsoftware.sbhub.protos.FibonacciSequence) obj;

    boolean result = true;
    result = result && (getVersion()
        == other.getVersion());
    result = result && (getCount()
        == other.getCount());
    result = result && getSequenceList()
        .equals(other.getSequenceList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    if (getSequenceCount() > 0) {
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciSequence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.townsendsoftware.sbhub.protos.FibonacciSequence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.townsendsoftware.sbhub.protos.FibonacciSequence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.townsendsoftware.sbhub.protos.FibonacciSequence)
      com.townsendsoftware.sbhub.protos.FibonacciSequenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.townsendsoftware.sbhub.protos.FibonacciSequence.class, com.townsendsoftware.sbhub.protos.FibonacciSequence.Builder.class);
    }

    // Construct using com.townsendsoftware.sbhub.protos.FibonacciSequence.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      count_ = 0;

      sequence_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_descriptor;
    }

    @java.lang.Override
    public com.townsendsoftware.sbhub.protos.FibonacciSequence getDefaultInstanceForType() {
      return com.townsendsoftware.sbhub.protos.FibonacciSequence.getDefaultInstance();
    }

    @java.lang.Override
    public com.townsendsoftware.sbhub.protos.FibonacciSequence build() {
      com.townsendsoftware.sbhub.protos.FibonacciSequence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.townsendsoftware.sbhub.protos.FibonacciSequence buildPartial() {
      com.townsendsoftware.sbhub.protos.FibonacciSequence result = new com.townsendsoftware.sbhub.protos.FibonacciSequence(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      result.count_ = count_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        sequence_ = java.util.Collections.unmodifiableList(sequence_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.sequence_ = sequence_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.townsendsoftware.sbhub.protos.FibonacciSequence) {
        return mergeFrom((com.townsendsoftware.sbhub.protos.FibonacciSequence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.townsendsoftware.sbhub.protos.FibonacciSequence other) {
      if (other == com.townsendsoftware.sbhub.protos.FibonacciSequence.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (!other.sequence_.isEmpty()) {
        if (sequence_.isEmpty()) {
          sequence_ = other.sequence_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureSequenceIsMutable();
          sequence_.addAll(other.sequence_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.townsendsoftware.sbhub.protos.FibonacciSequence parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.townsendsoftware.sbhub.protos.FibonacciSequence) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 2;</code>
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 2;</code>
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> sequence_ = java.util.Collections.emptyList();
    private void ensureSequenceIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        sequence_ = new java.util.ArrayList<java.lang.Long>(sequence_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public java.util.List<java.lang.Long>
        getSequenceList() {
      return java.util.Collections.unmodifiableList(sequence_);
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public int getSequenceCount() {
      return sequence_.size();
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public long getSequence(int index) {
      return sequence_.get(index);
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public Builder setSequence(
        int index, long value) {
      ensureSequenceIsMutable();
      sequence_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public Builder addSequence(long value) {
      ensureSequenceIsMutable();
      sequence_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public Builder addAllSequence(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureSequenceIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sequence_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 sequence = 4;</code>
     */
    public Builder clearSequence() {
      sequence_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.townsendsoftware.sbhub.protos.FibonacciSequence)
  }

  // @@protoc_insertion_point(class_scope:com.townsendsoftware.sbhub.protos.FibonacciSequence)
  private static final com.townsendsoftware.sbhub.protos.FibonacciSequence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.townsendsoftware.sbhub.protos.FibonacciSequence();
  }

  public static com.townsendsoftware.sbhub.protos.FibonacciSequence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FibonacciSequence>
      PARSER = new com.google.protobuf.AbstractParser<FibonacciSequence>() {
    @java.lang.Override
    public FibonacciSequence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FibonacciSequence(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FibonacciSequence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FibonacciSequence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.townsendsoftware.sbhub.protos.FibonacciSequence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

