// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sbhub.proto

package com.townsendsoftware.sbhub.protos;

/**
 * Protobuf type {@code com.townsendsoftware.sbhub.protos.FibonacciParameters}
 */
public  final class FibonacciParameters extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.townsendsoftware.sbhub.protos.FibonacciParameters)
    FibonacciParametersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FibonacciParameters.newBuilder() to construct.
  private FibonacciParameters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FibonacciParameters() {
    version_ = 0;
    sequenceSeed0_ = 0L;
    sequenceSeed1_ = 0L;
    iterations_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FibonacciParameters(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            sequenceSeed0_ = input.readInt64();
            break;
          }
          case 24: {

            sequenceSeed1_ = input.readInt64();
            break;
          }
          case 32: {

            iterations_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.townsendsoftware.sbhub.protos.FibonacciParameters.class, com.townsendsoftware.sbhub.protos.FibonacciParameters.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int SEQUENCESEED0_FIELD_NUMBER = 2;
  private long sequenceSeed0_;
  /**
   * <code>int64 sequenceSeed0 = 2;</code>
   */
  public long getSequenceSeed0() {
    return sequenceSeed0_;
  }

  public static final int SEQUENCESEED1_FIELD_NUMBER = 3;
  private long sequenceSeed1_;
  /**
   * <code>int64 sequenceSeed1 = 3;</code>
   */
  public long getSequenceSeed1() {
    return sequenceSeed1_;
  }

  public static final int ITERATIONS_FIELD_NUMBER = 4;
  private int iterations_;
  /**
   * <code>int32 iterations = 4;</code>
   */
  public int getIterations() {
    return iterations_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (sequenceSeed0_ != 0L) {
      output.writeInt64(2, sequenceSeed0_);
    }
    if (sequenceSeed1_ != 0L) {
      output.writeInt64(3, sequenceSeed1_);
    }
    if (iterations_ != 0) {
      output.writeInt32(4, iterations_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (sequenceSeed0_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, sequenceSeed0_);
    }
    if (sequenceSeed1_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, sequenceSeed1_);
    }
    if (iterations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, iterations_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.townsendsoftware.sbhub.protos.FibonacciParameters)) {
      return super.equals(obj);
    }
    com.townsendsoftware.sbhub.protos.FibonacciParameters other = (com.townsendsoftware.sbhub.protos.FibonacciParameters) obj;

    boolean result = true;
    result = result && (getVersion()
        == other.getVersion());
    result = result && (getSequenceSeed0()
        == other.getSequenceSeed0());
    result = result && (getSequenceSeed1()
        == other.getSequenceSeed1());
    result = result && (getIterations()
        == other.getIterations());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + SEQUENCESEED0_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSequenceSeed0());
    hash = (37 * hash) + SEQUENCESEED1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSequenceSeed1());
    hash = (37 * hash) + ITERATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getIterations();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.townsendsoftware.sbhub.protos.FibonacciParameters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.townsendsoftware.sbhub.protos.FibonacciParameters prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.townsendsoftware.sbhub.protos.FibonacciParameters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.townsendsoftware.sbhub.protos.FibonacciParameters)
      com.townsendsoftware.sbhub.protos.FibonacciParametersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.townsendsoftware.sbhub.protos.FibonacciParameters.class, com.townsendsoftware.sbhub.protos.FibonacciParameters.Builder.class);
    }

    // Construct using com.townsendsoftware.sbhub.protos.FibonacciParameters.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      sequenceSeed0_ = 0L;

      sequenceSeed1_ = 0L;

      iterations_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.townsendsoftware.sbhub.protos.SbHubMessages.internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_descriptor;
    }

    @java.lang.Override
    public com.townsendsoftware.sbhub.protos.FibonacciParameters getDefaultInstanceForType() {
      return com.townsendsoftware.sbhub.protos.FibonacciParameters.getDefaultInstance();
    }

    @java.lang.Override
    public com.townsendsoftware.sbhub.protos.FibonacciParameters build() {
      com.townsendsoftware.sbhub.protos.FibonacciParameters result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.townsendsoftware.sbhub.protos.FibonacciParameters buildPartial() {
      com.townsendsoftware.sbhub.protos.FibonacciParameters result = new com.townsendsoftware.sbhub.protos.FibonacciParameters(this);
      result.version_ = version_;
      result.sequenceSeed0_ = sequenceSeed0_;
      result.sequenceSeed1_ = sequenceSeed1_;
      result.iterations_ = iterations_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.townsendsoftware.sbhub.protos.FibonacciParameters) {
        return mergeFrom((com.townsendsoftware.sbhub.protos.FibonacciParameters)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.townsendsoftware.sbhub.protos.FibonacciParameters other) {
      if (other == com.townsendsoftware.sbhub.protos.FibonacciParameters.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getSequenceSeed0() != 0L) {
        setSequenceSeed0(other.getSequenceSeed0());
      }
      if (other.getSequenceSeed1() != 0L) {
        setSequenceSeed1(other.getSequenceSeed1());
      }
      if (other.getIterations() != 0) {
        setIterations(other.getIterations());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.townsendsoftware.sbhub.protos.FibonacciParameters parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.townsendsoftware.sbhub.protos.FibonacciParameters) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private long sequenceSeed0_ ;
    /**
     * <code>int64 sequenceSeed0 = 2;</code>
     */
    public long getSequenceSeed0() {
      return sequenceSeed0_;
    }
    /**
     * <code>int64 sequenceSeed0 = 2;</code>
     */
    public Builder setSequenceSeed0(long value) {
      
      sequenceSeed0_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sequenceSeed0 = 2;</code>
     */
    public Builder clearSequenceSeed0() {
      
      sequenceSeed0_ = 0L;
      onChanged();
      return this;
    }

    private long sequenceSeed1_ ;
    /**
     * <code>int64 sequenceSeed1 = 3;</code>
     */
    public long getSequenceSeed1() {
      return sequenceSeed1_;
    }
    /**
     * <code>int64 sequenceSeed1 = 3;</code>
     */
    public Builder setSequenceSeed1(long value) {
      
      sequenceSeed1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sequenceSeed1 = 3;</code>
     */
    public Builder clearSequenceSeed1() {
      
      sequenceSeed1_ = 0L;
      onChanged();
      return this;
    }

    private int iterations_ ;
    /**
     * <code>int32 iterations = 4;</code>
     */
    public int getIterations() {
      return iterations_;
    }
    /**
     * <code>int32 iterations = 4;</code>
     */
    public Builder setIterations(int value) {
      
      iterations_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 iterations = 4;</code>
     */
    public Builder clearIterations() {
      
      iterations_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.townsendsoftware.sbhub.protos.FibonacciParameters)
  }

  // @@protoc_insertion_point(class_scope:com.townsendsoftware.sbhub.protos.FibonacciParameters)
  private static final com.townsendsoftware.sbhub.protos.FibonacciParameters DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.townsendsoftware.sbhub.protos.FibonacciParameters();
  }

  public static com.townsendsoftware.sbhub.protos.FibonacciParameters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FibonacciParameters>
      PARSER = new com.google.protobuf.AbstractParser<FibonacciParameters>() {
    @java.lang.Override
    public FibonacciParameters parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FibonacciParameters(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FibonacciParameters> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FibonacciParameters> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.townsendsoftware.sbhub.protos.FibonacciParameters getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

