// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sbhub.proto

package com.townsendsoftware.sbhub.protos;

public interface FibonacciParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.townsendsoftware.sbhub.protos.FibonacciParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   */
  int getVersion();

  /**
   * <code>int64 sequenceSeed0 = 2;</code>
   */
  long getSequenceSeed0();

  /**
   * <code>int64 sequenceSeed1 = 3;</code>
   */
  long getSequenceSeed1();

  /**
   * <code>int32 iterations = 4;</code>
   */
  int getIterations();
}
