// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sbhub.proto

package com.townsendsoftware.sbhub.protos;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.townsendsoftware.sbhub.protos.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   */
  int getVersion();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.townsendsoftware.sbhub.protos.ResponseLevel level = 3;</code>
   */
  int getLevelValue();
  /**
   * <code>.com.townsendsoftware.sbhub.protos.ResponseLevel level = 3;</code>
   */
  com.townsendsoftware.sbhub.protos.ResponseLevel getLevel();
}
