// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sbhub.proto

package com.townsendsoftware.sbhub.protos;

/**
 * Protobuf enum {@code com.townsendsoftware.sbhub.protos.ResponseLevel}
 */
public enum ResponseLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <code>WARNING = 1;</code>
   */
  WARNING(1),
  /**
   * <code>ERROR = 2;</code>
   */
  ERROR(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <code>WARNING = 1;</code>
   */
  public static final int WARNING_VALUE = 1;
  /**
   * <code>ERROR = 2;</code>
   */
  public static final int ERROR_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ResponseLevel valueOf(int value) {
    return forNumber(value);
  }

  public static ResponseLevel forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return WARNING;
      case 2: return ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResponseLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResponseLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResponseLevel>() {
          public ResponseLevel findValueByNumber(int number) {
            return ResponseLevel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.townsendsoftware.sbhub.protos.SbHubMessages.getDescriptor().getEnumTypes().get(0);
  }

  private static final ResponseLevel[] VALUES = values();

  public static ResponseLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResponseLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.townsendsoftware.sbhub.protos.ResponseLevel)
}

