// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sbhub.proto

package com.townsendsoftware.sbhub.protos;

public final class SbHubMessages {
  private SbHubMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_townsendsoftware_sbhub_protos_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_townsendsoftware_sbhub_protos_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_townsendsoftware_sbhub_protos_FibonacciResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013sbhub.proto\022!com.townsendsoftware.sbhu" +
      "b.protos\"E\n\021FibonacciSequence\022\017\n\007version" +
      "\030\001 \001(\005\022\r\n\005count\030\002 \001(\005\022\020\n\010sequence\030\004 \003(\003\"" +
      "h\n\023FibonacciParameters\022\017\n\007version\030\001 \001(\005\022" +
      "\025\n\rsequenceSeed0\030\002 \001(\003\022\025\n\rsequenceSeed1\030" +
      "\003 \001(\003\022\022\n\niterations\030\004 \001(\005\"t\n\017ResponseMes" +
      "sage\022\017\n\007version\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022?" +
      "\n\005level\030\003 \001(\01620.com.townsendsoftware.sbh" +
      "ub.protos.ResponseLevel\"\375\001\n\021FibonacciRes" +
      "ponse\022\017\n\007version\030\001 \001(\005\022F\n\010sequence\030\002 \001(\013" +
      "24.com.townsendsoftware.sbhub.protos.Fib" +
      "onacciSequence\022J\n\nparameters\030\003 \001(\01326.com" +
      ".townsendsoftware.sbhub.protos.Fibonacci" +
      "Parameters\022C\n\007message\030\004 \001(\01322.com.townse" +
      "ndsoftware.sbhub.protos.ResponseMessage*" +
      "4\n\rResponseLevel\022\013\n\007SUCCESS\020\000\022\013\n\007WARNING" +
      "\020\001\022\t\n\005ERROR\020\002B4\n!com.townsendsoftware.sb" +
      "hub.protosB\rSbHubMessagesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_townsendsoftware_sbhub_protos_FibonacciSequence_descriptor,
        new java.lang.String[] { "Version", "Count", "Sequence", });
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_townsendsoftware_sbhub_protos_FibonacciParameters_descriptor,
        new java.lang.String[] { "Version", "SequenceSeed0", "SequenceSeed1", "Iterations", });
    internal_static_com_townsendsoftware_sbhub_protos_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_townsendsoftware_sbhub_protos_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_townsendsoftware_sbhub_protos_ResponseMessage_descriptor,
        new java.lang.String[] { "Version", "Message", "Level", });
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_townsendsoftware_sbhub_protos_FibonacciResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_townsendsoftware_sbhub_protos_FibonacciResponse_descriptor,
        new java.lang.String[] { "Version", "Sequence", "Parameters", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
